from __future__ import annotations

import argparse
from pathlib import Path
import re
import pandas as pd


def normalize_meter(value) -> str:
    """Normalize meter ids for robust joins."""
    if pd.isna(value):
        return ""
    s = str(value).strip().upper()
    s = re.sub(r"[^A-Z0-9]", "", s)
    return s


def clean_column_name(col: str) -> str:
    """Normalize Excel column names."""
    col = str(col).strip()
    col = col.replace("\n", " ")
    col = re.sub(r"\s+", " ", col)
    return col


def clean_mall_name_from_folder(folder_name: str) -> str:
    """
    Create a cleaner human mall name from a folder like:
    '01. V1_Ambar Fashion Mall Tuxtla'
    """
    s = str(folder_name).strip()
    s = re.sub(r"^\d+\.\s*", "", s)  # remove leading '01. '
    return s


def machine_mall_id(name: str) -> str:
    """Create a machine-friendly mall identifier."""
    s = str(name).strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[\s-]+", "_", s)
    return s.strip("_")


def standardize_inventory_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Rename common Fraternity spreadsheet columns to stable names.
    Extend this map if future spreadsheets vary slightly.
    """
    rename_map = {
        "NOMBRE DEL CC": "mall_name_excel",
        "CLIENTE": "cliente",
        "NOMBRE COMERCIAL": "nombre_comercial",
        "SUBGIRO_COMERCIAL": "subgiro_comercial",
        "SUBGIRO COMERCIAL": "subgiro_comercial",
        "MTS2": "area_m2",
        "M2": "area_m2",
        "TIPO LOCAL": "tipo_local",
        "No de Local": "local_id",
        "No. de Local": "local_id",
        "No. De Local": "local_id",
        "NIVEL": "nivel",
        "Carga Conectada (kW)": "carga_conectada_kw",
        "Carga conectada (kW)": "carga_conectada_kw",
        "Carga Conectada KW": "carga_conectada_kw",
        "Demanda Contratada (kW)": "demanda_contratada_kw",
        "Demanda contratada (kW)": "demanda_contratada_kw",
        "Demanda Contratada KW": "demanda_contratada_kw",
        "CONSUMO REAL": "consumo_real",
        "TARIFA": "tarifa_excel",
        "No. De medidor": "medidor",
        "No. de medidor": "medidor",
        "No de medidor": "medidor",
        "MEDIDOR": "medidor",
        "Observaciones": "observaciones",
        "OBSERVACIONES": "observaciones",
    }

    df = df.copy()
    df.columns = [clean_column_name(c) for c in df.columns]
    df = df.rename(columns=rename_map)

    # Drop Excel artifact columns like Unnamed: 17
    keep_cols = [c for c in df.columns if not str(c).startswith("Unnamed:")]
    df = df[keep_cols]

    return df


def load_inventory_folder(portfolio_root: Path) -> pd.DataFrame:
    """
    Recursively find Inventory.xlsx files under the mall portfolio root.

    Expected structure:
      portfolio_root/
        01. V1_Ambar Fashion Mall Tuxtla/
          0. Datos Generales/
            Inventory.xlsx
    """
    files = sorted(portfolio_root.rglob("Inventory.xlsx"))
    if not files:
        raise FileNotFoundError(f"No Inventory.xlsx files found under {portfolio_root}")

    frames = []
    for f in files:
        try:
            df = pd.read_excel(f)
        except Exception as e:
            print(f"⚠️ Skipping unreadable file: {f} ({e})")
            continue

        df = standardize_inventory_columns(df)

        # Infer mall folder from path:
        # .../<mall_folder>/0. Datos Generales/Inventory.xlsx
        try:
            mall_folder = f.parent.parent.name
        except Exception:
            mall_folder = ""

        mall_name_clean = clean_mall_name_from_folder(mall_folder)
        mall_id = machine_mall_id(mall_name_clean)

        df["mall_folder"] = mall_folder
        df["mall_name_clean"] = mall_name_clean
        df["mall_id"] = mall_id
        df["source_inventory_file"] = str(f)

        frames.append(df)

    if not frames:
        raise ValueError(f"Found Inventory.xlsx files, but none could be loaded from {portfolio_root}")

    inventory = pd.concat(frames, ignore_index=True)

    if "medidor" not in inventory.columns:
        raise ValueError("No meter column found in inventory spreadsheets after standardization.")

    inventory["medidor_norm"] = inventory["medidor"].map(normalize_meter)

    # Numeric cleanup
    for c in ["area_m2", "carga_conectada_kw", "demanda_contratada_kw", "consumo_real"]:
        if c in inventory.columns:
            inventory[c] = pd.to_numeric(inventory[c], errors="coerce")

    return inventory


def load_tenant_fingerprints(path: Path) -> pd.DataFrame:
    """Load tenant_fingerprints.csv generated by analyze.py."""
    df = pd.read_csv(path)

    if "medidor" not in df.columns:
        raise ValueError("tenant_fingerprints.csv must contain 'medidor' column")

    df["medidor_norm"] = df["medidor"].map(normalize_meter)

    for c in ["kwh_sum", "kwh_mean", "kwh_median", "importe_sum", "importe_mean", "mxn_per_kwh_mean", "bills_count"]:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")

    return df


def build_integrated_dataset(tenant_fp: pd.DataFrame, inventory: pd.DataFrame) -> pd.DataFrame:
    """
    Merge inventory descriptors with energy fingerprints.

    Join key:
      medidor_norm

    Notes:
    - We intentionally do not merge on mall name yet.
    - Meter number is the strongest identifier.
    - Mall name agreement is audited afterward using mall_match.
    """
    merged = inventory.merge(
        tenant_fp,
        how="left",
        on="medidor_norm",
        suffixes=("_inventory", "_energy"),
    )

    # Reconcile meter columns
    if "medidor_inventory" in merged.columns:
        merged["medidor_final"] = merged["medidor_inventory"]
    elif "medidor_energy" in merged.columns:
        merged["medidor_final"] = merged["medidor_energy"]
    else:
        merged["medidor_final"] = merged.get("medidor", "")

    # Mall agreement audit
    if "mall_folder_inventory" in merged.columns and "mall_folder_energy" in merged.columns:
        merged["mall_match"] = (
            merged["mall_folder_inventory"].astype(str).str.strip()
            == merged["mall_folder_energy"].astype(str).str.strip()
        )
    else:
        merged["mall_match"] = pd.NA

    # Derived indicators
    if "area_m2" in merged.columns and "kwh_mean" in merged.columns:
        merged["kwh_per_m2_mean"] = merged["kwh_mean"] / merged["area_m2"]

    if "area_m2" in merged.columns and "kwh_sum" in merged.columns:
        merged["kwh_per_m2_total"] = merged["kwh_sum"] / merged["area_m2"]

    if "demanda_contratada_kw" in merged.columns and "kwh_mean" in merged.columns:
        merged["kwh_per_kw_contracted"] = merged["kwh_mean"] / merged["demanda_contratada_kw"]

    if "tarifa_excel" in merged.columns and "tarifa_mode" in merged.columns:
        merged["tariff_match"] = (
            merged["tarifa_excel"].astype(str).str.upper().str.strip()
            == merged["tarifa_mode"].astype(str).str.upper().str.strip()
        )

    return merged


def build_join_report(inventory: pd.DataFrame, merged: pd.DataFrame) -> dict:
    """Produce a small integration quality report."""
    total_inventory = len(inventory)

    matched = int(merged["kwh_sum"].notna().sum()) if "kwh_sum" in merged.columns else 0
    unmatched = total_inventory - matched

    mall_match_count = int(merged["mall_match"].fillna(False).sum()) if "mall_match" in merged.columns else 0
    tariff_match_count = int(merged["tariff_match"].fillna(False).sum()) if "tariff_match" in merged.columns else 0

    report = {
        "inventory_rows": total_inventory,
        "matched_rows": matched,
        "unmatched_rows": unmatched,
        "match_rate": round(matched / total_inventory, 4) if total_inventory else 0.0,
        "mall_match_rows": mall_match_count,
        "tariff_match_rows": tariff_match_count,
    }

    return report


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Integrate Fraternity mall inventory sheets with tenant energy fingerprints."
    )
    parser.add_argument(
        "--tenant-fp",
        default="data/logs/analysis/tenant_fingerprints.csv",
        help="Path to tenant_fingerprints.csv",
    )
    parser.add_argument(
        "--inventory-dir",
        default="data/mall_inventory",
        help="Portfolio root containing mall folders with 0. Datos Generales/Inventory.xlsx",
    )
    parser.add_argument(
        "--outdir",
        default="data/logs/analysis",
        help="Output directory",
    )
    args = parser.parse_args()

    tenant_fp_path = Path(args.tenant_fp)
    inventory_dir = Path(args.inventory_dir)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    tenant_fp = load_tenant_fingerprints(tenant_fp_path)
    inventory = load_inventory_folder(inventory_dir)
    integrated = build_integrated_dataset(tenant_fp, inventory)
    report = build_join_report(inventory, integrated)

    integrated_path = outdir / "integrated_tenant_dataset.csv"
    unmatched_path = outdir / "unmatched_inventory_rows.csv"
    report_path = outdir / "integration_report.csv"

    integrated.to_csv(integrated_path, index=False)

    if "kwh_sum" in integrated.columns:
        integrated[integrated["kwh_sum"].isna()].to_csv(unmatched_path, index=False)
    else:
        integrated.to_csv(unmatched_path, index=False)

    pd.DataFrame([report]).to_csv(report_path, index=False)

    print(f"✅ Wrote: {integrated_path}")
    print(f"✅ Wrote: {unmatched_path}")
    print(f"✅ Wrote: {report_path}")
    print(f"✅ Match rate: {report['match_rate']:.2%}")


if __name__ == "__main__":
    main()